// models/15minPrices.js
import mongoose from 'mongoose';

const germany15MinSchema = new mongoose.Schema({
  'Delivery day': String,
  'Hour 1 Q1': Number, 'Hour 1 Q2': Number, 'Hour 1 Q3': Number, 'Hour 1 Q4': Number,
  'Hour 2 Q1': Number, 'Hour 2 Q2': Number, 'Hour 2 Q3': Number, 'Hour 2 Q4': Number,
  'Hour 3A Q1': Number, 'Hour 3A Q2': Number, 'Hour 3A Q3': Number, 'Hour 3A Q4': Number,
  'Hour 3B Q1': Number, 'Hour 3B Q2': Number, 'Hour 3B Q3': Number, 'Hour 3B Q4': Number,
  'Hour 4 Q1': Number, 'Hour 4 Q2': Number, 'Hour 4 Q3': Number, 'Hour 4 Q4': Number,
  'Hour 5 Q1': Number, 'Hour 5 Q2': Number, 'Hour 5 Q3': Number, 'Hour 5 Q4': Number,
  'Hour 6 Q1': Number, 'Hour 6 Q2': Number, 'Hour 6 Q3': Number, 'Hour 6 Q4': Number,
  'Hour 7 Q1': Number, 'Hour 7 Q2': Number, 'Hour 7 Q3': Number, 'Hour 7 Q4': Number,
  'Hour 8 Q1': Number, 'Hour 8 Q2': Number, 'Hour 8 Q3': Number, 'Hour 8 Q4': Number,
  'Hour 9 Q1': Number, 'Hour 9 Q2': Number, 'Hour 9 Q3': Number, 'Hour 9 Q4': Number,
  'Hour 10 Q1': Number, 'Hour 10 Q2': Number, 'Hour 10 Q3': Number, 'Hour 10 Q4': Number,
  'Hour 11 Q1': Number, 'Hour 11 Q2': Number, 'Hour 11 Q3': Number, 'Hour 11 Q4': Number,
  'Hour 12 Q1': Number, 'Hour 12 Q2': Number, 'Hour 12 Q3': Number, 'Hour 12 Q4': Number,
  'Hour 13 Q1': Number, 'Hour 13 Q2': Number, 'Hour 13 Q3': Number, 'Hour 13 Q4': Number,
  'Hour 14 Q1': Number, 'Hour 14 Q2': Number, 'Hour 14 Q3': Number, 'Hour 14 Q4': Number,
  'Hour 15 Q1': Number, 'Hour 15 Q2': Number, 'Hour 15 Q3': Number, 'Hour 15 Q4': Number,
  'Hour 16 Q1': Number, 'Hour 16 Q2': Number, 'Hour 16 Q3': Number, 'Hour 16 Q4': Number,
  'Hour 17 Q1': Number, 'Hour 17 Q2': Number, 'Hour 17 Q3': Number, 'Hour 17 Q4': Number,
  'Hour 18 Q1': Number, 'Hour 18 Q2': Number, 'Hour 18 Q3': Number, 'Hour 18 Q4': Number,
  'Hour 19 Q1': Number, 'Hour 19 Q2': Number, 'Hour 19 Q3': Number, 'Hour 19 Q4': Number,
  'Hour 20 Q1': Number, 'Hour 20 Q2': Number, 'Hour 20 Q3': Number, 'Hour 20 Q4': Number,
  'Hour 21 Q1': Number, 'Hour 21 Q2': Number, 'Hour 21 Q3': Number, 'Hour 21 Q4': Number,
  'Hour 22 Q1': Number, 'Hour 22 Q2': Number, 'Hour 22 Q3': Number, 'Hour 22 Q4': Number,
  'Hour 23 Q1': Number, 'Hour 23 Q2': Number, 'Hour 23 Q3': Number, 'Hour 23 Q4': Number,
  'Hour 24 Q1': Number, 'Hour 24 Q2': Number, 'Hour 24 Q3': Number, 'Hour 24 Q4': Number,
  Minimum: Number,
  Maximum: Number,
  Baseload: Number,
  Peakload: Number,
  'Off-peak': Number,
  'Off-peak 2': Number,
  'Off-peak 1': Number,
  Night: Number,
  'Late morning': Number,
  'Early afternoon': Number,
  Evening: Number,
  'Early morning': Number,
  Business: Number,
  Afternoon: Number,
  'Middle night': Number,
  Morning: Number,
  'High noon': Number,
  'Rush hour': Number,
  'Sun peak': Number
}, { strict: true, collection: '15minPrices' });

export default mongoose.models['15minPrices'] || mongoose.model('15minPrices', germany15MinSchema);